
language: java
jdk:
  - openjdk11
  - openjdk8

cache:
  directories:
  - $HOME/.m2
  

branches:
  only:
    - /.*/
before_install:
  - sudo apt-get update

jobs:
  include:
      ## Test Stage  ##
    - stage: Build App
      #if: branch = master
      script:
      - mvn clean install -DskipTests=true




notifications:
  email:
    on_failure: never
    on_success: never  
