
language: java
jdk:
  - openjdk11
  - oraclejdk11
  - openjdk8
  - oraclejdk8

cache:
  directories:
  - $HOME/.m2
  

branches:
  only:
    - /.*/
before_install:
  - sudo apt-get update

install:
  - mvn clean package -DskipTests=true
  
jobs:
  include:
      ## Test Stage  ##
    - stage: Build App
      #if: branch = master
      script:
      - mvn clean install -DskipTests=true
      
    ## Build and Package Stage  ##
    - stage: Build App
      if: branch = master
      script:
      - mvn clean package -DskipTests=true



notifications:
  email:
    on_failure: never
    on_success: never  
