# Application Properties
spring:
  application:
    name: Liquibase Test
  # Jpa Properties
  datasource:
    #spring.datasource.url=jdbc:mysql://localhost:3306/springsecuritydb?useSSL=false
    url: ${spring.datasource.url}
    username: ${spring.datasource.username}
    password: ${spring.datasource.password}
  jpa:
    hibernate:
      ddl-auto: none

  # Liquibase properties
  devtools:
    restart:
      enabled: true
  liquibase:
    contexts: dev

## Server Properties
server:
  port: ${server.port}

management:
  endpoints:
    web:
      exposure:
        include: ["health","info"]
  endpoint:
    auditevents:
      enabled: true

